# =========================
# PostgreSQL
# =========================

spring.datasource.url=jdbc:postgresql://localhost:5432/voiceai
spring.datasource.username=postgres
spring.datasource.password=123456

# =========================
# JPA / Hibernate
# =========================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# Ollama
# =========================

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen2.5

# =========================
# Servidor
# =========================

server.port=8080